name: inception 

services:
  nginx: 
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - wordpress
  wordpress: 
    build: ./requirements/wordpress
    container_name: wp-php
    restart: always
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_db_password
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    secrets: 
      - wp_db_password
      - wp_admin_password
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    secrets: 
      - mysql_root_password
      - mysql_password
volumes: 
  db_data: 
  wp_data: 
secrets: 
  mysql_root_password: 
    file: ../secrets/mysql_root_password.txt
  mysql_password: 
    file: ../secrets/mysql_password.txt
  wp_db_password: 
    file: ../secrets/wp_db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
